#!/usr/bin/env python3
"""Pin the Iltero CLI that the `setup` action installs.

Run this from the repository root when moving to another CLI commit:

    scripts/lock-cli.py CLI_CHECKOUT SCHEMAS_COMMIT

CLI_CHECKOUT is a checkout of iltero-cli at the commit to pin. SCHEMAS_COMMIT
is the iltero-schemas commit that CLI commit is tested against.

The script writes two files under setup/:

- cli-sources.txt: the two commits the action installs from source.
- cli-requirements.txt: every other package the CLI needs at run time, plus
  the build backend for the two source installs, each with its version and
  the SHA-256 hashes from the CLI's own lock file.
"""

import re
import subprocess
import sys
import tomllib
from pathlib import Path

SETUP_DIR = Path(__file__).resolve().parent.parent / "setup"
COMMIT = re.compile(r"[0-9a-f]{40}")
# The source installs are built with this backend, so it and its
# dependencies are locked as well.
BUILD_BACKEND = "hatchling"
REQUIREMENT_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*")
# Installed from source at a pinned commit, not from the lock.
SOURCE_PACKAGES = frozenset({"iltero-schemas"})


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def head_commit(checkout: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(checkout), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def requirement_lines(package: dict) -> list[str]:
    hashes = sorted(entry["hash"] for entry in package.get("files", []))
    if not hashes:
        fail(f"{package['name']} has no hashes in the lock file")
    marker = package.get("marker")
    head = f"{package['name']}=={package['version']}"
    if marker:
        head += f" ; {marker}"
    return [f"{head} \\"] + [f"    --hash={value} \\" for value in hashes[:-1]] + [f"    --hash={hashes[-1]}"]


def with_dependencies(root: str, packages: dict[str, dict]) -> set[str]:
    """Return the name of a locked package and of every locked package it needs."""
    found: set[str] = set()
    pending = [root]
    while pending:
        name = pending.pop()
        if name in found:
            continue
        if name not in packages:
            fail(f"the lock file has no entry for {name}")
        found.add(name)
        for requirement in packages[name].get("dependencies", []):
            match = REQUIREMENT_NAME.match(requirement)
            if match is None:
                fail(f"cannot read the requirement '{requirement}' of {name}")
            dependency = match.group(0).lower().replace("_", "-").replace(".", "-")
            # A dependency limited to another Python version may be absent from the lock.
            if dependency in packages or ";" not in requirement:
                pending.append(dependency)
    return found


def main() -> None:
    if len(sys.argv) != 3:
        fail("usage: scripts/lock-cli.py CLI_CHECKOUT SCHEMAS_COMMIT")
    checkout = Path(sys.argv[1])
    schemas_commit = sys.argv[2]
    if not COMMIT.fullmatch(schemas_commit):
        fail("SCHEMAS_COMMIT must be a full 40-character commit")
    cli_commit = head_commit(checkout)

    lock = tomllib.loads((checkout / "pdm.lock").read_text(encoding="utf-8"))
    packages = {package["name"]: package for package in lock["package"]}
    build = with_dependencies(BUILD_BACKEND, packages)
    selected = [
        package
        for package in packages.values()
        if package["name"] not in SOURCE_PACKAGES
        and ("default" in package.get("groups", []) or package["name"] in build)
    ]

    lines = [
        "# Generated by scripts/lock-cli.py. Do not edit.",
        f"# Iltero CLI commit: {cli_commit}",
    ]
    for package in sorted(selected, key=lambda entry: entry["name"]):
        lines.extend(requirement_lines(package))
    (SETUP_DIR / "cli-requirements.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (SETUP_DIR / "cli-sources.txt").write_text(
        f"iltero-schemas {schemas_commit}\niltero-cli {cli_commit}\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
